Extension { #name : #Number }

{ #category : #'*Aconcagua-Convenience' }
Number >> celsius [
	^ Measure amount: self unit: DefaultUnits soleInstance celsius

]

{ #category : #'*Aconcagua-Convenience' }
Number >> centavo [
	^ Measure amount: self unit: DefaultUnits soleInstance centavo

]

{ #category : #'*Aconcagua-Convenience' }
Number >> centimeter [
	^ Measure amount: self unit: DefaultUnits soleInstance centimeter

]

{ #category : #'*Aconcagua-Convenience' }
Number >> decameter [
	^ Measure amount: self unit: DefaultUnits soleInstance decameter

]

{ #category : #'*Aconcagua-Convenience' }
Number >> decimeter [
	^ Measure amount: self unit: DefaultUnits soleInstance decimeter

]

{ #category : #'*Aconcagua-Convenience' }
Number >> dollar [
	^ Measure amount: self unit: DefaultUnits soleInstance dollar

]

{ #category : #'*Aconcagua-Convenience' }
Number >> euro [
	^ Measure amount: self unit: DefaultUnits soleInstance euro

]

{ #category : #'*Aconcagua-Convenience' }
Number >> euroCent [
	^ Measure amount: self unit: DefaultUnits soleInstance euroCent

]

{ #category : #'*Aconcagua-Convenience' }
Number >> fahrenheit [
	^ Measure amount: self unit: DefaultUnits soleInstance fahrenheit

]

{ #category : #'*Aconcagua-Convenience' }
Number >> hectometer [
	^ Measure amount: self unit: DefaultUnits soleInstance hectometer

]

{ #category : #'*Aconcagua-Convenience' }
Number >> hourUnit [
	^ Measure amount: self unit: DefaultUnits soleInstance hour

]

{ #category : #'*Aconcagua-Convenience' }
Number >> kelvin [
	^ Measure amount: self unit: DefaultUnits soleInstance kelvin

]

{ #category : #'*Aconcagua-Convenience' }
Number >> kilometer [
	^ Measure amount: self unit: DefaultUnits soleInstance kilometer

]

{ #category : #'*Aconcagua-Convenience' }
Number >> meter [
	^ Measure amount: self unit: DefaultUnits soleInstance meter

]

{ #category : #'*Aconcagua-Convenience' }
Number >> millimeter [
	^ Measure amount: self unit: DefaultUnits soleInstance millimeter

]

{ #category : #'*Aconcagua-Convenience' }
Number >> millisecondUnit [
	^ Measure amount: self unit: DefaultUnits soleInstance millisecond

]

{ #category : #'*Aconcagua-Convenience' }
Number >> minuteUnit [
	^ Measure amount: self unit: DefaultUnits soleInstance minute

]

{ #category : #'*Aconcagua-Convenience' }
Number >> peso [
	^ Measure amount: self unit: DefaultUnits soleInstance peso

]

{ #category : #'*Aconcagua-Convenience' }
Number >> quarter [
	^ Measure amount: self unit: DefaultUnits soleInstance quarter

]

{ #category : #'*Aconcagua-Convenience' }
Number >> secondUnit [
	^ Measure amount: self unit: DefaultUnits soleInstance second

]

{ #category : #'*Aconcagua-Convenience' }
Number >> semester [
	^ Measure amount: self unit: DefaultUnits soleInstance semester

]

{ #category : #'*Aconcagua-Convenience' }
Number >> trimester [
	^ Measure amount: self unit: DefaultUnits soleInstance trimester

]

{ #category : #'*Aconcagua-Convenience' }
Number >> weekUnit [
	^ Measure amount: self unit: DefaultUnits soleInstance week

]

{ #category : #'*Aconcagua-Convenience' }
Number >> yearUnit [
	^ Measure amount: self unit: DefaultUnits soleInstance year

]
